-- DISABLE RLS FOR ADMIN TABLES TO ALLOW FRONTEND ADMIN PANEL TO SAVE
ALTER TABLE public.offer_config DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.products DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.category_banners DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.color_variants DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.homepage_banners DISABLE ROW LEVEL SECURITY;
